// ============================================================================
// units/_hors-fiches.js — CE FICHIER N'EST CHARGE PAR AUCUNE PAGE.
//
// Les 85 images ci-dessous etaient enregistrees dans l'ancien registre unique
// mais ne sont referencees par aucune fiche de data/*.json : unites retirees
// d'un build, ou cartes extraites puis finalement non posees. Les PNG
// correspondants existent tous sur le disque (verifie).
//
// Elles sont conservees ici plutot que supprimees : pour en reutiliser une,
// deplacer sa ligne dans le js/units/<faction>.js concerne.
// ============================================================================

const unitImagesHorsFiches = {
  tebRiccoRepublicanGuard: 'assets/units/tebRiccoRepublicanGuard.png',
  poulainKnightsFoot: 'assets/units/poulainKnightsFoot.png',
  scorpionBrt: 'assets/units/scorpionBrt.png',
  ronin: 'assets/units/ronin.png',
  mushaCavNaginata: 'assets/units/mushaCavNaginata.png',
  greatStagKnights: 'assets/units/greatStagKnights.png',
  ironDaemonRoR: 'assets/units/ironDaemonRoR.png',
  infernalCastellan: 'assets/units/infernalCastellan.png',
  sorcererProphet: 'assets/units/sorcererProphet.png',
  albGiant: 'assets/units/albGiant.png',
  arbWarElephant: 'assets/units/arbWarElephant.png',
  arbFireEfreet: 'assets/units/arbFireEfreet.png',
  arbGrandBombard: 'assets/units/arbGrandBombard.png',
  arbFlyingCarpets: 'assets/units/arbFlyingCarpets.png',
  arbTempestDjinn: 'assets/units/arbTempestDjinn.png',
  arbDesertSpirit: 'assets/units/arbDesertSpirit.png',
  fimFiannaFimmShields: 'assets/units/fimFiannaFimmShields.png',
  fimBogBeastRaiders: 'assets/units/fimBogBeastRaiders.png',
  kaptainBoss: 'assets/units/kaptainBoss.png',
  freebootaBigUns: 'assets/units/freebootaBigUns.png',
  freebootaBoyzSwords: 'assets/units/freebootaBoyzSwords.png',
  freebootaHeavyWeap: 'assets/units/freebootaHeavyWeap.png',
  orcBattleTankAA: 'assets/units/orcBattleTankAA.png',
  orcBattleship: 'assets/units/orcBattleship.png',
  freebootaStikbooma: 'assets/units/freebootaStikbooma.png',
  riverTrollsArmored: 'assets/units/riverTrollsArmored.png',
  giantGreenskins: 'assets/units/giantGreenskins.png',
  forestGoblinArchers: 'assets/units/forestGoblinArchers.png',
  featheredScuttlas: 'assets/units/featheredScuttlas.png',
  colossalSquig: 'assets/units/colossalSquig.png',
  hellcannonWoC: 'assets/units/hellcannonWoC.png',
  salamanderHuntingPack: 'assets/units/salamanderHuntingPack.png',
  hellPitAbomination: 'assets/units/hellPitAbomination.png',
  crossbowmen: 'assets/units/crossbowmen.png',
  warWagons: 'assets/units/warWagons.png',
  empireKnights: 'assets/units/empireKnights.png',
  skeletonHoplites: 'assets/units/skeletonHoplites.png',
  necrosphinx: 'assets/units/necrosphinx.png',
  deckGunners: 'assets/units/deckGunners.png',
  vampireFleetCaptain: 'assets/units/vampireFleetCaptain.png',
  theOldOne: 'assets/units/theOldOne.png',
  darkProphetess: 'assets/units/darkProphetess.png',
  kahled: 'assets/units/kahled.png',
  bloodKnightChampion: 'assets/units/bloodKnightChampion.png',
  bloodkinThrall: 'assets/units/bloodkinThrall.png',
  thrallKnights: 'assets/units/thrallKnights.png',
  doomWolfKnights: 'assets/units/doomWolfKnights.png',
  bloodDragonRoR: 'assets/units/bloodDragonRoR.png',
  astrolicheTheak: 'assets/units/astrolicheTheak.png',
  jadeShugengan: 'assets/units/jadeShugengan.png',
  jiangMasterNecro: 'assets/units/jiangMasterNecro.png',
  jiangBanshee: 'assets/units/jiangBanshee.png',
  jiangGraveGuardCrossbow: 'assets/units/jiangGraveGuardCrossbow.png',
  jiangZombieArcher: 'assets/units/jiangZombieArcher.png',
  jiangZombieSpear: 'assets/units/jiangZombieSpear.png',
  undeadLongma: 'assets/units/undeadLongma.png',
  dracolith: 'assets/units/dracolith.png',
  shuimu: 'assets/units/shuimu.png',
  warCompass: 'assets/units/warCompass.png',
  shadowLantern: 'assets/units/shadowLantern.png',
  cathayMonk: 'assets/units/cathayMonk.png',
  syreen: 'assets/units/syreen.png',
  copsewight: 'assets/units/copsewight.png',
  bretonnianWight: 'assets/units/bretonnianWight.png',
  cantankerousBellends: 'assets/units/cantankerousBellends.png',
  giantSnail: 'assets/units/giantSnail.png',
  hngTorguud: 'assets/units/hngTorguud.png',
  hngChaosVultures: 'assets/units/hngChaosVultures.png',
  // Gulgulet Sandgrinder (The Famished).
  arabyOgreBulls: 'assets/units/arabyOgreBulls.png',
  norscanGiant: 'assets/units/norscanGiant.png',
  skeggiChampions: 'assets/units/skeggiChampions.png',
  norscanWhalers: 'assets/units/norscanWhalers.png',
  bjornlingSpearmen: 'assets/units/bjornlingSpearmen.png',
  sarlMarauders: 'assets/units/sarlMarauders.png',
  sarlBerserkers: 'assets/units/sarlBerserkers.png',
  yusakMarauders: 'assets/units/yusakMarauders.png',
  yusakHuntersThrowingAxes: 'assets/units/yusakHuntersThrowingAxes.png',
  yusakHorsemen: 'assets/units/yusakHorsemen.png',
  kurganMarauderGreatWeapons: 'assets/units/kurganMarauderGreatWeapons.png',
  kurganMarauderChampions: 'assets/units/kurganMarauderChampions.png',
  kurganHuntersJavelins: 'assets/units/kurganHuntersJavelins.png',
  victorGuttman: 'assets/units/victorGuttman.png',
  savageSkavenslaveSlingers: 'assets/units/savageSkavenslaveSlingers.png',
  warPigs: 'assets/units/warPigs.png',
  garbagsSkavenWolfChariots: 'assets/units/garbagsSkavenWolfChariots.png'
};
