// ============================================================================
// units/greenskins.js — images d'unites de la faction « greenskins », et d'elle seule.
//
// Charge uniquement par greenskins.html, juste avant js/app.js qui s'en sert dans
// unitCardHtml(). Chaque cle correspond au champ "icon" d'une unite dans
// data/greenskins.json ; la valeur est le chemin de l'image reelle.
//
// Ces 151 entrees vivaient auparavant dans un registre unique de 2063 images
// que CHAQUE page chargeait en entier, soit 117 Ko pour n'afficher que sa
// propre faction. Le decoupage est purement mecanique : meme objet global
// `unitImages`, memes cles, meme code de rendu dans app.js.
//
// A connaitre avant d'editer : ajouter une unite dans
// data/greenskins.json impose d'ajouter sa cle ICI aussi. Une cle absente
// affiche une carte sans image et sans message d'erreur ; le script
// tools/verifier-icones.ps1 detecte precisement ce cas.
// ============================================================================

const unitImages = {
  nobberFangadoom: 'assets/portraits/nobberFangadoom.png',
  grimgor: 'assets/portraits/grimgor.png',
  skarsnik: 'assets/portraits/skarsnik.png',
  wurrzag: 'assets/portraits/wurrzag.png',
  grom: 'assets/portraits/grom.png',
  azhag: 'assets/portraits/azhag.png',
  gorbad: 'assets/portraits/gorbad.png',
  gorfang: 'assets/portraits/gorfang.png',
  barbozza: 'assets/portraits/barbozza.png',
  gnarlyTreehugga: 'assets/portraits/gnarlyTreehugga.png',
  drogmak: 'assets/portraits/drogmak.png',
  gormok: 'assets/portraits/gormok.png',
  skarfangBlackskull: 'assets/portraits/skarfangBlackskull.png',
  blackOrcs: 'assets/units/blackOrcs.png',
  borlokDaRippa: 'assets/units/borlokDaRippa.png',
  blackOrcsDualWeapons: 'assets/units/blackOrcsDualWeapons.png',
  ironjaws: 'assets/units/ironjaws.png',
  blackOrcKrossboyz: 'assets/units/blackOrcKrossboyz.png',
  scrapLauncha: 'assets/units/scrapLauncha.png',
  blackOrcBoarBoyz: 'assets/units/blackOrcBoarBoyz.png',
  blackOrcBoarChariots: 'assets/units/blackOrcBoarChariots.png',
  wyvernRiders: 'assets/units/wyvernRiders.png',
  biggaBoltThrowa: 'assets/units/biggaBoltThrowa.png',
  wildBoars: 'assets/units/wildBoars.png',
  krimsonKillerz: 'assets/units/krimsonKillerz.png',
  orcBoyz: 'assets/units/orcBoyz.png',
  orcBoyzSpears: 'assets/units/orcBoyzSpears.png',
  goblinsSpears: 'assets/units/goblinsSpears.png',
  goblinArchers: 'assets/units/goblinArchers.png',
  orcBoarBoyBigUns: 'assets/units/orcBoarBoyBigUns.png',
  brokenTusksMob: 'assets/units/brokenTusksMob.png',
  ramnbow: 'assets/units/ramnbow.png',
  orklid: 'assets/units/orklid.png',
  daPatcha: 'assets/units/daPatcha.png',
  freebootaBoyzSpear: 'assets/units/freebootaBoyzSpear.png',
  freebootaShoota: 'assets/units/freebootaShoota.png',
  freebootaSplitta: 'assets/units/freebootaSplitta.png',
  crabBoys: 'assets/units/crabBoys.png',
  orkKommandoz: 'assets/units/orkKommandoz.png',
  khureshFirstCompany: 'assets/units/khureshFirstCompany.png',
  piratedGyrocopter: 'assets/units/piratedGyrocopter.png',
  deathshrieka: 'assets/units/deathshrieka.png',
  orcBattleTank: 'assets/units/orcBattleTank.png',
  rokkitBombardia: 'assets/units/rokkitBombardia.png',
  harpoonLuncha: 'assets/units/harpoonLuncha.png',
  doomDiverCatapults: 'assets/units/doomDiverCatapults.png',
  nightGoblins: 'assets/units/nightGoblins.png',
  spiderRiders: 'assets/units/spiderRiders.png',
  snorkoTheSneak: 'assets/units/snorkoTheSneak.png',
  daWarlordsBoyz: 'assets/units/daWarlordsBoyz.png',
  nightGoblinSquigHoppers: 'assets/units/nightGoblinSquigHoppers.png',
  durkitsSquigs: 'assets/units/durkitsSquigs.png',
  arachnarokSpider: 'assets/units/arachnarokSpider.png',
  savageOrcs: 'assets/units/savageOrcs.png',
  savageOrcArrerBoyz: 'assets/units/savageOrcArrerBoyz.png',
  savageOrcBoarBoyz: 'assets/units/savageOrcBoarBoyz.png',
  savageOrcBigUns: 'assets/units/savageOrcBigUns.png',
  stoneTrolls: 'assets/units/stoneTrolls.png',
  riverTrolls: 'assets/units/riverTrolls.png',
  daSwampFings: 'assets/units/daSwampFings.png',
  snotlingPumpWagons: 'assets/units/snotlingPumpWagons.png',
  goblinRockLobbers: 'assets/units/goblinRockLobbers.png',
  orcBigUns: 'assets/units/orcBigUns.png',
  forestGoblins: 'assets/units/forestGoblins.png',
  forestGoblinsSpears: 'assets/units/forestGoblinsSpears.png',
  forestGoblinsBows: 'assets/units/forestGoblinsBows.png',
  forestGoblinSpiderRiderArchers: 'assets/units/forestGoblinSpiderRiderArchers.png',
  deffCreeperz: 'assets/units/deffCreeperz.png',
  arachnarokQueen: 'assets/units/arachnarokQueen.png',
  orcArrerBoyz: 'assets/units/orcArrerBoyz.png',
  squigHerd: 'assets/units/squigHerd.png',
  goblinBoltThrowa: 'assets/units/goblinBoltThrowa.png',
  snaglasDeffThrowa: 'assets/units/snaglasDeffThrowa.png',
  blackOrcBigBoss: 'assets/units/blackOrcBigBoss.png',
  orcShaman: 'assets/units/orcShaman.png',
  nightGoblinShaman: 'assets/units/nightGoblinShaman.png',
  savageOrcGreatShaman: 'assets/units/savageOrcGreatShaman.png',
  goblinGreatShaman: 'assets/units/goblinGreatShaman.png',
  forestGoblinShaman: 'assets/units/forestGoblinShaman.png',
  teefRobberz: 'assets/units/teefRobberz.png',
  moonHowlers: 'assets/units/moonHowlers.png',
  giantRiverTrollHag: 'assets/units/giantRiverTrollHag.png',
  ironOrcBoyz: 'assets/units/ironOrcBoyz.png',
  gurthok: 'assets/units/gurthok.png',
  darkLandDrakeRider: 'assets/units/darkLandDrakeRider.png',
  darkLandOrcBoyz: 'assets/units/darkLandOrcBoyz.png',
  daBronzenBastardz: 'assets/units/daBronzenBastardz.png',
  terrorOfGorgoth: 'assets/units/terrorOfGorgoth.png',
  breakerzOfZharr: 'assets/units/breakerzOfZharr.png',
  darkLandOrcBigUns: 'assets/units/darkLandOrcBigUns.png',
  darkLandBulwarkz: 'assets/units/darkLandBulwarkz.png',
  scrapShootaz: 'assets/units/scrapShootaz.png',
  darkLandDrake: 'assets/units/darkLandDrake.png',
  ironSquigs: 'assets/units/ironSquigs.png',
  goblinBigBoss: 'assets/units/goblinBigBoss.png',
  ironOrcBoyzCrossbows: 'assets/units/ironOrcBoyzCrossbows.png',
  ironOrcBigUns: 'assets/units/ironOrcBigUns.png',
  ironOrcBigUnsGreatWeapons: 'assets/units/ironOrcBigUnsGreatWeapons.png',
  ironOrcBrutez: 'assets/units/ironOrcBrutez.png',
  ironOrcBrutezGreatWeapons: 'assets/units/ironOrcBrutezGreatWeapons.png',
  ironOrcBoarBoyBigUns: 'assets/units/ironOrcBoarBoyBigUns.png',
  colossalIronSquig: 'assets/units/colossalIronSquig.png',
  gorkstomper: 'assets/units/gorkstomper.png',
  morksMaw: 'assets/units/morksMaw.png',
  grakBeastbasha: 'assets/portraits/grakBeastbasha.png',
  sporctacus: 'assets/portraits/sporctacus.png',
  tinittFourEyes: 'assets/portraits/tinittFourEyes.png',
  gitillaDaHunter: 'assets/portraits/gitillaDaHunter.png',
  savageOrcsSpears: 'assets/units/savageOrcsSpears.png',
  savageOrcBigUnsBows: 'assets/units/savageOrcBigUnsBows.png',
  savageManeaters: 'assets/units/savageManeaters.png',
  savageManeatersIronfists: 'assets/units/savageManeatersIronfists.png',
  savageManeatersDualMaces: 'assets/units/savageManeatersDualMaces.png',
  savageGiant: 'assets/units/savageGiant.png',
  sasquatches: 'assets/units/sasquatches.png',
  nightGoblinsSpears: 'assets/units/nightGoblinsSpears.png',
  squigGobba: 'assets/units/squigGobba.png',
  uncagedOgres: 'assets/units/uncagedOgres.png',
  harbothsBlackmountainBoyz: 'assets/units/harbothsBlackmountainBoyz.png',
  littleGork: 'assets/units/littleGork.png',
  // Snagla Grobspit n'a pas de carte d'unite en vanilla : portrait reutilise.
  snaglaGrobspit: 'assets/units/snaglaGrobspit.png',
  forestGoblinShamanSpider: 'assets/units/forestGoblinShamanSpider.png',
  savageOrcShaman: 'assets/units/savageOrcShaman.png',
  goblinWolfRiders: 'assets/units/goblinWolfRiders.png',
  goblinWolfRidersBows: 'assets/units/goblinWolfRidersBows.png',
  goblinWolfChariot: 'assets/units/goblinWolfChariot.png',
  morgrubbsMangyMarauders: 'assets/units/morgrubbsMangyMarauders.png',
  forestGoblinSpiderRiders: 'assets/units/forestGoblinSpiderRiders.png',
  savageOrcsBows: 'assets/units/savageOrcsBows.png',
  plagueclawCatapult: 'assets/units/plagueclawCatapult.png',
  chieftain: 'assets/units/chieftain.png',
  borgutFacebeater: 'assets/units/borgutFacebeater.png',
  durkolEyeGouger: 'assets/units/durkolEyeGouger.png',
  duffskul: 'assets/units/duffskul.png',
  kapnSkabend: 'assets/units/kapnSkabend.png',
  bigRedUn: 'assets/units/bigRedUn.png',
  taugrekTheThrottler: 'assets/units/taugrekTheThrottler.png',
  blacktoof: 'assets/units/blacktoof.png',
  bulgrugWarpslave: 'assets/units/bulgrugWarpslave.png',
  rugludBonechewer: 'assets/units/rugludBonechewer.png',
  littleGorkHero: 'assets/units/littleGorkHero.png',
  garbag: 'assets/portraits/garbag.png',
  spite: 'assets/portraits/spite.png',
  goblinWolfRatRidersPoison: 'assets/units/goblinWolfRatRidersPoison.png',
  skavenSquiggybackRiders: 'assets/units/skavenSquiggybackRiders.png',
  ironclawKnights: 'assets/units/ironclawKnights.png',
  goblinWolfRatRiders: 'assets/units/goblinWolfRatRiders.png',
  ruffRiders: 'assets/units/ruffRiders.png',
  unguthTheVile: 'assets/portraits/unguthTheVile.png',
  wolfclawReavers: 'assets/units/wolfclawReavers.png',
  daAcidBurpa: 'assets/units/daAcidBurpa.png',
  daBlackBeard: 'assets/units/daBlackBeard.png'
};
