// ============================================================================
// units/norsca.js — images d'unites de la faction « norsca », et d'elle seule.
//
// Charge uniquement par norsca.html, juste avant js/app.js qui s'en sert dans
// unitCardHtml(). Chaque cle correspond au champ "icon" d'une unite dans
// data/norsca.json ; la valeur est le chemin de l'image reelle.
//
// Ces 127 entrees vivaient auparavant dans un registre unique de 2063 images
// que CHAQUE page chargeait en entier, soit 117 Ko pour n'afficher que sa
// propre faction. Le decoupage est purement mecanique : meme objet global
// `unitImages`, memes cles, meme code de rendu dans app.js.
//
// A connaitre avant d'editer : ajouter une unite dans
// data/norsca.json impose d'ajouter sa cle ICI aussi. Une cle absente
// affiche une carte sans image et sans message d'erreur ; le script
// tools/verifier-icones.ps1 detecte precisement ce cas.
// ============================================================================

const unitImages = {
  chaosSpawn: 'assets/units/chaosSpawn.png',
  chaosWarriorsKhorne: 'assets/units/chaosWarriorsKhorne.png',
  wulfrik: 'assets/portraits/wulfrik.png',
  throgg: 'assets/portraits/throgg.png',
  sayl: 'assets/portraits/sayl.png',
  egil: 'assets/portraits/egil.png',
  chaosKnightsLances: 'assets/units/chaosKnightsLances.png',
  maraudersOfKhorne: 'assets/units/maraudersOfKhorne.png',
  worshippersOfTheCrow: 'assets/units/worshippersOfTheCrow.png',
  mawsOfSavagery: 'assets/units/mawsOfSavagery.png',
  tusklingOfMogwrath: 'assets/units/tusklingOfMogwrath.png',
  theGreatMawherdOfBloodfjord: 'assets/units/theGreatMawherdOfBloodfjord.png',
  marauderChampions: 'assets/units/marauderChampions.png',
  marauderBerserkersNorsca: 'assets/units/marauderBerserkersNorsca.png',
  brutesOfTheHound: 'assets/units/brutesOfTheHound.png',
  fraygerd: 'assets/units/fraygerd.png',
  hrefna: 'assets/units/hrefna.png',
  marauderGreatWeaponsNorsca: 'assets/units/marauderGreatWeaponsNorsca.png',
  marauderHorsemenThrowingAxesNorsca: 'assets/units/marauderHorsemenThrowingAxesNorsca.png',
  feralMammothNorsca: 'assets/units/feralMammothNorsca.png',
  maraudersNorsca: 'assets/units/maraudersNorsca.png',
  norscanIceTrolls: 'assets/units/norscanIceTrolls.png',
  norscanTrolls: 'assets/units/norscanTrolls.png',
  norscanIceWolves: 'assets/units/norscanIceWolves.png',
  dazharrDoomaxe: 'assets/units/dazharrDoomaxe.png',
  marauderBearmenGreatWeapons: 'assets/units/marauderBearmenGreatWeapons.png',
  marauderBearmen: 'assets/units/marauderBearmen.png',
  kurganHorsemenDualWeapons: 'assets/units/kurganHorsemenDualWeapons.png',
  cursdEttinRunecaller: 'assets/units/cursdEttinRunecaller.png',
  norscanWarhounds: 'assets/units/norscanWarhounds.png',
  shamanSorcerer: 'assets/units/shamanSorcerer.png',
  icehornMarauders: 'assets/units/icehornMarauders.png',
  mistStalkers: 'assets/units/mistStalkers.png',
  ridersOfTheMightySerpent: 'assets/units/ridersOfTheMightySerpent.png',
  valbrandFireblade: 'assets/portraits/valbrandFireblade.png',
  surthaLenk: 'assets/portraits/surthaLenk.png',
  thorgarTheBloodedOne: 'assets/portraits/thorgarTheBloodedOne.png',
  volrikClawhand: 'assets/portraits/volrikClawhand.png',
  marauderHuntersJavelins: 'assets/units/marauderHuntersJavelins.png',
  marauderChampionsGreatWeapons: 'assets/units/marauderChampionsGreatWeapons.png',
  warMammoth: 'assets/units/warMammoth.png',
  beastsOfTashnar: 'assets/units/beastsOfTashnar.png',
  soulcrusher: 'assets/units/soulcrusher.png',
  adellaOfTheThousandMouths: 'assets/portraits/adellaOfTheThousandMouths.png',
  hakkaTheAesling: 'assets/portraits/hakkaTheAesling.png',
  einarrSigdansson: 'assets/portraits/einarrSigdansson.png',
  ulfricGrondal: 'assets/portraits/ulfricGrondal.png',
  theDodvakt: 'assets/units/theDodvakt.png',
  corruptedCarnosaurKhorne: 'assets/units/corruptedCarnosaurKhorne.png',
  corruptedBastiladonKhorne: 'assets/units/corruptedBastiladonKhorne.png',
  corruptedBastiladonSlaanesh: 'assets/units/corruptedBastiladonSlaanesh.png',
  corruptedTroglodonSlaanesh: 'assets/units/corruptedTroglodonSlaanesh.png',
  bjornlingHuscarls: 'assets/units/bjornlingHuscarls.png',
  theTrawledThrone: 'assets/units/theTrawledThrone.png',
  haraldursHuscarls: 'assets/units/haraldursHuscarls.png',
  highJarlGeimdall: 'assets/portraits/highJarlGeimdall.png',
  haraldWhyrlas: 'assets/portraits/haraldWhyrlas.png',
  akkorakTheCrow: 'assets/portraits/akkorakTheCrow.png',
  huernTheWolf: 'assets/portraits/huernTheWolf.png',
  werekinOfFijgard: 'assets/units/werekinOfFijgard.png',
  skinWolves: 'assets/units/skinWolves.png',
  skinWolvesArmoured: 'assets/units/skinWolvesArmoured.png',
  theWolvesOfNaglfari: 'assets/units/theWolvesOfNaglfari.png',
  northernManeatersIronfists: 'assets/units/northernManeatersIronfists.png',
  birnaTheHuntress: 'assets/portraits/birnaTheHuntress.png',
  drenokJohansen: 'assets/portraits/drenokJohansen.png',
  surthaEk: 'assets/portraits/surthaEk.png',
  sargathTheVain: 'assets/portraits/sargathTheVain.png',
  sarlHunters: 'assets/units/sarlHunters.png',
  stalkersOfTheKaltiDelta: 'assets/units/stalkersOfTheKaltiDelta.png',
  theColdVoider: 'assets/units/theColdVoider.png',
  marauderIceWolfChariots: 'assets/units/marauderIceWolfChariots.png',
  chaosChariots: 'assets/units/chaosChariots.png',
  jarlGrydal: 'assets/portraits/jarlGrydal.png',
  olafWolfhound: 'assets/portraits/olafWolfhound.png',
  grofturFiskauga: 'assets/portraits/grofturFiskauga.png',
  branBearheart: 'assets/portraits/branBearheart.png',
  bearmenOfUrslo: 'assets/units/bearmenOfUrslo.png',
  capturedFeralBears: 'assets/units/capturedFeralBears.png',
  ustaTheWitch: 'assets/units/ustaTheWitch.png',
  berusOfVeigs: 'assets/units/berusOfVeigs.png',
  rafnOflatisson: 'assets/units/rafnOflatisson.png',
  orgrimTheWanderer: 'assets/units/orgrimTheWanderer.png',
  jarlHafskael: 'assets/units/jarlHafskael.png',
  verdandi: 'assets/units/verdandi.png',
  hildrTheReaver: 'assets/units/hildrTheReaver.png',
  ulsdau: 'assets/units/ulsdau.png',
  graill: 'assets/units/graill.png',
  olgBlodsalt: 'assets/units/olgBlodsalt.png',
  lokjarBjoergir: 'assets/units/lokjarBjoergir.png',
  larsMortensen: 'assets/units/larsMortensen.png',
  haftagg: 'assets/units/haftagg.png',
  ernstVonKammler: 'assets/units/ernstVonKammler.png',
  sorenHoarder: 'assets/units/sorenHoarder.png',
  jarlOdaWinterclaw: 'assets/units/jarlOdaWinterclaw.png',
  zarUzelek: 'assets/units/zarUzelek.png',
  fishbrainsMonolith: 'assets/units/fishbrainsMonolith.png',
  skeggiMarauderGreatWeapons: 'assets/units/skeggiMarauderGreatWeapons.png',
  skeggiHuntersJavelins: 'assets/units/skeggiHuntersJavelins.png',
  skeggiSpearmen: 'assets/units/skeggiSpearmen.png',
  feralYmir: 'assets/units/feralYmir.png',
  orgrimsScourge: 'assets/units/orgrimsScourge.png',
  hooksOfHjolda: 'assets/units/hooksOfHjolda.png',
  bjornlingMarauderGreatWeapons: 'assets/units/bjornlingMarauderGreatWeapons.png',
  bjornlingChampions: 'assets/units/bjornlingChampions.png',
  bjornlingHuntersJavelins: 'assets/units/bjornlingHuntersJavelins.png',
  sarlChampionsGreatWeapons: 'assets/units/sarlChampionsGreatWeapons.png',
  sarlHuntersThrowingAxes: 'assets/units/sarlHuntersThrowingAxes.png',
  marauderWarWagons: 'assets/units/marauderWarWagons.png',
  aeslingHuntersJavelins: 'assets/units/aeslingHuntersJavelins.png',
  aeslingMarauderBerserkers: 'assets/units/aeslingMarauderBerserkers.png',
  yusakSpearmen: 'assets/units/yusakSpearmen.png',
  yusakDevotedMarauders: 'assets/units/yusakDevotedMarauders.png',
  baersonlingMarauders: 'assets/units/baersonlingMarauders.png',
  baersonlingChampionsGreatWeapons: 'assets/units/baersonlingChampionsGreatWeapons.png',
  baersonlingHuntersThrowingAxes: 'assets/units/baersonlingHuntersThrowingAxes.png',
  graelingMarauderChampions: 'assets/units/graelingMarauderChampions.png',
  icefangMarauder: 'assets/units/icefangMarauder.png',
  tyeddiBearsson: 'assets/units/tyeddiBearsson.png',
  corruptedFeralIceBears: 'assets/units/corruptedFeralIceBears.png',
  harrowfin: 'assets/units/harrowfin.png',
  maulkernTheRavager: 'assets/units/maulkernTheRavager.png',
  surthasRevenge: 'assets/units/surthasRevenge.png',
  iceGolem: 'assets/units/iceGolem.png',
  greaterIceGolem: 'assets/units/greaterIceGolem.png',
  frostWyrm: 'assets/units/frostWyrm.png',
  ziadZhang: 'assets/portraits/ziadZhang.png'
};
