// ============================================================================
// units/skaven.js — images d'unites de la faction « skaven », et d'elle seule.
//
// Charge uniquement par skaven.html, juste avant js/app.js qui s'en sert dans
// unitCardHtml(). Chaque cle correspond au champ "icon" d'une unite dans
// data/skaven.json ; la valeur est le chemin de l'image reelle.
//
// Ces 169 entrees vivaient auparavant dans un registre unique de 2063 images
// que CHAQUE page chargeait en entier, soit 117 Ko pour n'afficher que sa
// propre faction. Le decoupage est purement mecanique : meme objet global
// `unitImages`, memes cles, meme code de rendu dans app.js.
//
// A connaitre avant d'editer : ajouter une unite dans
// data/skaven.json impose d'ajouter sa cle ICI aussi. Une cle absente
// affiche une carte sans image et sans message d'erreur ; le script
// tools/verifier-icones.ps1 detecte precisement ce cas.
// ============================================================================

const unitImages = {
  queek: 'assets/portraits/queek.png',
  skrolk: 'assets/portraits/skrolk.png',
  tretch: 'assets/portraits/tretch.png',
  ikitclaw: 'assets/portraits/ikitClaw.png',
  snikch: 'assets/portraits/snikch.png',
  throt: 'assets/portraits/throt.png',
  feskit: 'assets/portraits/feskit.png',
  burnbarrels: 'assets/units/burnbarrels.png',
  crawlersInTheDark: 'assets/units/crawlersInTheDark.png',
  glowSkurrys: 'assets/units/glowSkurrys.png',
  stormverminHalberds: 'assets/units/stormverminHalberds.png',
  stormverminShields: 'assets/units/stormverminShields.png',
  clanratsShields: 'assets/units/clanratsShields.png',
  warpfireThrowers: 'assets/units/warpfireThrowers.png',
  ratOgres: 'assets/units/ratOgres.png',
  skavenslaveSlingers: 'assets/units/skavenslaveSlingers.png',
  skavenslaveSpears: 'assets/units/skavenslaveSpears.png',
  skavenslaves: 'assets/units/skavenslaves.png',
  plagueMonks: 'assets/units/plagueMonks.png',
  plagueMonkCenserBearers: 'assets/units/plagueMonkCenserBearers.png',
  plagueclawCatapult: 'assets/units/plagueclawCatapult.png',
  poisonWindGlobadiers: 'assets/units/poisonWindGlobadiers.png',
  deathRunners: 'assets/units/deathRunners.png',
  doomwheel: 'assets/units/doomwheel.png',
  warplockJezzails: 'assets/units/warplockJezzails.png',
  ratlingGuns: 'assets/units/ratlingGuns.png',
  eshinTriads: 'assets/units/eshinTriads.png',
  nightRunners: 'assets/units/nightRunners.png',
  nightRunnersSlings: 'assets/units/nightRunnersSlings.png',
  gutterRunners: 'assets/units/gutterRunners.png',
  gutterRunnerSlingers: 'assets/units/gutterRunnerSlingers.png',
  broodHorror: 'assets/units/broodHorror.png',
  wolfRats: 'assets/units/wolfRats.png',
  mutantRatOgre: 'assets/units/mutantRatOgre.png',
  warpLightningCannon: 'assets/units/warpLightningCannon.png',
  chieftain: 'assets/units/chieftain.png',
  plaguePriest: 'assets/units/plaguePriest.png',
  warlockEngineer: 'assets/units/warlockEngineer.png',
  packmaster: 'assets/units/packmaster.png',
  assassinHero: 'assets/units/assassinHero.png',
  skvBlackMask: 'assets/units/skvBlackMask.png',
  councilGuard: 'assets/units/councilGuard.png',
  blightscabsPlaguepack: 'assets/units/blightscabsPlaguepack.png',
  ikitsZzzzapZzzzap: 'assets/units/ikitsZzzzapZzzzap.png',
  ikshasTriads: 'assets/units/ikshasTriads.png',
  pitFightersHellsDeep: 'assets/units/pitFightersHellsDeep.png',
  // Héros légendaires Skaven (mod SCM Legendary Characters).
  fylchSharptail: 'assets/units/fylchSharptail.png',
  lurklox: 'assets/units/lurklox.png',
  veskit: 'assets/units/veskit.png',
  ikkHackflay: 'assets/units/ikkHackflay.png',
  skaBloodtail: 'assets/units/skaBloodtail.png',
  forgemasterIronSkull: 'assets/portraits/forgemasterIronSkull.png',
  skarrikSpinemanglr: 'assets/portraits/skarrikSpinemanglr.png',
  duneskulkSkreekblade: 'assets/portraits/duneskulkSkreekblade.png',
  trikstabGribnode: 'assets/portraits/trikstabGribnode.png',
  ferrikClanrats: 'assets/units/ferrikClanrats.png',
  ferrikClanratsSpears: 'assets/units/ferrikClanratsSpears.png',
  ferrikStormverminShields: 'assets/units/ferrikStormverminShields.png',
  ratsketeers: 'assets/units/ratsketeers.png',
  shieldThrowerBattery: 'assets/units/shieldThrowerBattery.png',
  savageClanrats: 'assets/units/savageClanrats.png',
  savageClanratSpears: 'assets/units/savageClanratSpears.png',
  savageSkavenslaves: 'assets/units/savageSkavenslaves.png',
  dunedaggers: 'assets/units/dunedaggers.png',
  goblinSlaves: 'assets/units/goblinSlaves.png',
  savageOrcSlaves: 'assets/units/savageOrcSlaves.png',
  bigGameHunters: 'assets/units/bigGameHunters.png',
  gnarlbones: 'assets/units/gnarlbones.png',
  sandratEnslavers: 'assets/units/sandratEnslavers.png',
  pusbags: 'assets/units/pusbags.png',
  pusbagsSlings: 'assets/units/pusbagsSlings.png',
  rottenRodentsDual: 'assets/units/rottenRodentsDual.png',
  vrrtkinStormvermin: 'assets/units/vrrtkinStormvermin.png',
  vrrtkinDeathWindMortars: 'assets/units/vrrtkinDeathWindMortars.png',
  vrrtkinRatOgres: 'assets/units/vrrtkinRatOgres.png',
  turntails: 'assets/units/turntails.png',
  misericordeOfMordheim: 'assets/portraits/misericordeOfMordheim.png',
  rathan: 'assets/portraits/rathan.png',
  krethakGoretail: 'assets/portraits/krethakGoretail.png',
  archPontifexSitch: 'assets/portraits/archPontifexSitch.png',
  nightRunnersWarplockPistols: 'assets/units/nightRunnersWarplockPistols.png',
  eshinSorcerer: 'assets/units/eshinSorcerer.png',
  noiseChanters: 'assets/units/noiseChanters.png',
  ratonettes: 'assets/units/ratonettes.png',
  ratonetteChariot: 'assets/units/ratonetteChariot.png',
  mirrorVermin: 'assets/units/mirrorVermin.png',
  brassfangsDualAxe: 'assets/units/brassfangsDualAxe.png',
  brassfangsGreataxe: 'assets/units/brassfangsGreataxe.png',
  bloodverminGreatsword: 'assets/units/bloodverminGreatsword.png',
  bloodverminDualAxe: 'assets/units/bloodverminDualAxe.png',
  emberskullBombardiers: 'assets/units/emberskullBombardiers.png',
  wrathstormPyroclasts: 'assets/units/wrathstormPyroclasts.png',
  skullhunters: 'assets/units/skullhunters.png',
  fleshharvesters: 'assets/units/fleshharvesters.png',
  frothingWolfRatsPoison: 'assets/units/frothingWolfRatsPoison.png',
  greatPoxRat: 'assets/units/greatPoxRat.png',
  festeringChantor: 'assets/units/festeringChantor.png',
  grrzkRoteye: 'assets/portraits/grrzkRoteye.png',
  poxtooth: 'assets/portraits/poxtooth.png',
  nurglitch: 'assets/portraits/nurglitch.png',
  blightTenscratch: 'assets/portraits/blightTenscratch.png',
  verminkeepers: 'assets/units/verminkeepers.png',
  lamplighters: 'assets/units/lamplighters.png',
  scuttlers: 'assets/units/scuttlers.png',
  underEmpireSpiderRiders: 'assets/units/underEmpireSpiderRiders.png',
  vermsGiantRats: 'assets/units/vermsGiantRats.png',
  giantUnderEmpireBat: 'assets/units/giantUnderEmpireBat.png',
  ratSpawns: 'assets/units/ratSpawns.png',
  beastsOfDecay: 'assets/units/beastsOfDecay.png',
  bilekinBrotherhood: 'assets/units/bilekinBrotherhood.png',
  slimeblades: 'assets/units/slimeblades.png',
  plaguevermin: 'assets/units/plaguevermin.png',
  gristlTwitchslice: 'assets/portraits/gristlTwitchslice.png',
  rikzikSeepage: 'assets/portraits/rikzikSeepage.png',
  szikVilepot: 'assets/portraits/szikVilepot.png',
  skretchHalfDead: 'assets/portraits/skretchHalfDead.png',
  vicissBaukis: 'assets/portraits/vicissBaukis.png',
  tidesqueaker: 'assets/portraits/tidesqueaker.png',
  skurvyGunneryWarlocks: 'assets/portraits/skurvyGunneryWarlocks.png',
  stinkingThing: 'assets/units/stinkingThing.png',
  skurryStabbers: 'assets/units/skurryStabbers.png',
  pitFighters: 'assets/units/pitFighters.png',
  pitVermin: 'assets/units/pitVermin.png',
  theBrethren: 'assets/units/theBrethren.png',
  crooktailRatSpawns: 'assets/units/crooktailRatSpawns.png',
  theWrithing: 'assets/units/theWrithing.png',
  theDefiled: 'assets/units/theDefiled.png',
  theScaredlessLess: 'assets/units/theScaredlessLess.png',
  theBecoming: 'assets/units/theBecoming.png',
  skurvyWarpFireGunShips: 'assets/units/skurvyWarpFireGunShips.png',
  skurvyDeckGun: 'assets/units/skurvyDeckGun.png',
  skurvyDeckMortar: 'assets/units/skurvyDeckMortar.png',
  skurvyCrewratShields: 'assets/units/skurvyCrewratShields.png',
  skurvyCrewratSpears: 'assets/units/skurvyCrewratSpears.png',
  skurvySlaveBombers: 'assets/units/skurvySlaveBombers.png',
  skurvyStormverminWarpmuskets: 'assets/units/skurvyStormverminWarpmuskets.png',
  skurvySniper: 'assets/portraits/skurvySniper.png',
  theDecaying: 'assets/units/theDecaying.png',
  forgeGuardCaptain: 'assets/portraits/forgeGuardCaptain.png',
  ferrikForgebinder: 'assets/portraits/ferrikForgebinder.png',
  beaststalker: 'assets/portraits/beaststalker.png',
  wildspeaker: 'assets/portraits/wildspeaker.png',
  masterGlobadier: 'assets/portraits/masterGlobadier.png',
  gnawlitchShun: 'assets/portraits/gnawlitchShun.png',
  skulkFellpaw: 'assets/portraits/skulkFellpaw.png',
  eshinSorcererWarplockPistol: 'assets/portraits/eshinSorcererWarplockPistol.png',
  skullpriest: 'assets/portraits/skullpriest.png',
  bloodsqueaker: 'assets/portraits/bloodsqueaker.png',
  swarmcaller: 'assets/portraits/swarmcaller.png',
  broodmothers: 'assets/units/broodmothers.png',
  prikprangsPorkPack: 'assets/units/prikprangsPorkPack.png',
  clanVulknTailslashers: 'assets/units/clanVulknTailslashers.png',
  morskittarsHellion: 'assets/units/morskittarsHellion.png',
  nattyBuboesSharpshooters: 'assets/units/nattyBuboesSharpshooters.png',
  teethBreakers: 'assets/units/teethBreakers.png',
  virulentBatteries: 'assets/units/virulentBatteries.png',
  initiatesOfNurglitch: 'assets/units/initiatesOfNurglitch.png',
  chainedOnes: 'assets/units/chainedOnes.png',
  skullsplinters: 'assets/units/skullsplinters.png',
  bonefodder: 'assets/units/bonefodder.png',
  burrowCrackers: 'assets/units/burrowCrackers.png',
  trenchbeasts: 'assets/units/trenchbeasts.png',
  theHellbeastOfSeepGore: 'assets/units/theHellbeastOfSeepGore.png',
  hellPitHorrors: 'assets/units/hellPitHorrors.png',
  ironskins: 'assets/units/ironskins.png',
  deathDealers: 'assets/units/deathDealers.png',
  theDoombringers: 'assets/units/theDoombringers.png',
  eyeTakers: 'assets/units/eyeTakers.png',
  visktrinsDeathSquad: 'assets/units/visktrinsDeathSquad.png',
  wheelzOfDooom: 'assets/units/wheelzOfDooom.png'
};
